import React ,{ useContext }  from 'react';
import { StyleSheet , Dimensions } from 'react-native';

const styles= StyleSheet.create({
    container: {
        flex: 1, 
        backgroundColor: "white",
    },
    homepage: {
        padding:10, 
        justifyContent: 'center',
        textAlign:"center",
        alignItems:"center",
        backgroundColor: "white",
    },
    card:{
        justifyContent: 'center',
        textAlign:"center",
        alignItems:"center",
        elevation:5,
        backgroundColor: "#fff",
        width:"100%",
        height: 220,
        marginBottom:5,
    },
    h1:{
        color:"black",
        fontSize:34,
        fontWeight:"700",
        textAlign:"center",
        width:"100%",
    },
    h3:{
        color:"black",
        fontSize:20,
        fontWeight:"500",
    },
    p2:{
        color:"black",
        fontSize:16,
        fontWeight:"300",
    },
    p:{
        color:"blue",
        fontSize:12,
        width:"100%",
        textAlign:"center",
        margin:0,
    },
      ActionButton:{
        width:"100%",
        height:50,
        bottom:0,
        borderWidth:0.5,
        borderColor:"grey",
        justifyContent: 'center',
        alignItems:"center",
        position:"absolute",
      },
    logout:{  
        position:"absolute",
        bottom:0,
        height:60,
        width:"100%",
        backgroundColor:"transparent",
        justifyContent: 'center',
        alignItems:"center",
        padding:1,
    },
    logoutBotton:{
        marginTop:2,
        backgroundColor:"blue",
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: "100%",
        height: 50,
        elevation:3,
        borderRadius:10,
    },
    Buttontext:{
        color:"white",
        fontSize:18,
        width:"100%",
        textAlign:"center",
        margin:0,
    },
    searchInput :{
        marginTop:2,
        flexDirection: 'row',
        alignItems: 'center',
        width: "94%",
        paddingVertical: 2,
        paddingHorizontal: 4,
        borderRadius: 10,
        backgroundColor: "white",
        height: 50,
        borderColor:"blue",
        elevation:1,
    },
    searchInputArea:   {
        position: 'relative',  
        top:0,
        backgroundColor:"grey",
        height:60,
        width:'100%',
        justifyContent:"center",
        alignItems:"center",
    },
    list:{
        flex: 1,
        height:60,
        width:'100%',
        paddingVertical: 0.2,
        backgroundColor: "white",
        flexDirection: 'row',
        alignItems:'center',
    },
    appidentity:{
        display: 'flex',
        flex: 1, 
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: "center", 
        height:"100%",
    },
    appstatus:{
        display: 'flex',
        flex: 1, 
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: "center", 
        height:"100%",
    },
    ManageAppBox:{
        justifyContent: 'center',
        alignItems: "center", 
        backgroundColor: "white",
        paddingVertical:20,
    },
    ManageAppBoxOption:{
        width:"100%",
        height:60,
        flexDirection: 'row',
        padding:15,
        elevation:1,
    },
    ManageAppBoxOptionText:{
        flex:1,
        color:"black",
        fontSize:24,
        fontWeight:"600",
        display: 'flex', 
        justifyContent: 'flex-start',
    },
    eventContainer:{
        padding:15,
    },
    event:{
        padding:5,
    },
    eventlist:{
        width:"100%",
        height:60,
        borderBottomWidth:0.9,
        borderColor:"grey",
        flexDirection:"column",
    },
    dropdown: {
        backgroundColor: 'white',
        borderBottomColor: 'gray',
        borderBottomWidth: 0.5,
        marginTop: 20,
    },
    item: {
        paddingVertical: 17,
        paddingHorizontal: 4,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    textItem: {
        flex: 1,
        fontSize: 16,
    },
    shadow: {
        shadowColor: '#000',
        shadowOffset: {
        width: 0,
        height: 1,
        },
        shadowOpacity: 0.2,
        shadowRadius: 1.41,
        elevation: 2,
    },
    icon: {
        marginRight: 5,
        width: 18,
        height: 18,
    },
});

export default styles;